**Rachel Jasmine Canaman** <br>
DS4A

### Laboratory Task 5 ###

**1. Perform Standard Imports**

In [1]:
import torch
import numpy as np
import sys

**2. Create a function called set_seed() that accepts seed: int as a parameter, this function must return nothing but just set the seed to a certain value.**

In [2]:
def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)

**3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the set_seed() function and use 42 as the seed parameter.**

In [3]:
import random

In [4]:
set_seed(42)

arr = np.random.randint(0,5, size=6)
print(arr)

[3 4 2 4 4 1]


**4. Create a tensor "x" from the array above**

In [5]:
x = torch.from_numpy(arr)
print(x)

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)


**5. Change the dtype of x from int32 to int64**

In [6]:
x = x.to(torch.int64)

print(x)
print(x.dtype)

tensor([3, 4, 2, 4, 4, 1])
torch.int64


**6. Reshape x into a 3x2 tensor** <br>
There are several ways to do this.


In [7]:
x = x.reshape(3,2)

print(x)

tensor([[3, 4],
        [2, 4],
        [4, 1]])


**7. Return the right-hand column of tensor x**

In [8]:
rh = x[:,1]

print(rh)

tensor([4, 4, 1])


**8. Without changing x, return a tensor of square values of x** <br>
There are several ways to do this.

In [9]:
x_square = x**2
print()

**9. Create a tensor y with the same number of elements as x, that can be matrix-multiplied with x** <br>
Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive). Use 42 as seed.
Think about what shape it should have to permit matrix multiplication.

In [10]:
y = torch.randint(0,5, (2,3))
torch.manual_seed(42)

y

tensor([[4, 3, 3],
        [4, 0, 3]])

**10. Find the matrix product of x and y.**

In [11]:
matrix_product = torch.matmul(x,y)
matrix_product

tensor([[28,  9, 21],
        [24,  6, 18],
        [20, 12, 15]])